# Generated by Django 3.2.4 on 2021-06-08 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20210608_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='id',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='course', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='topiclesson',
            name='url',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_name', models.CharField(max_length=150, verbose_name='Социальная сеть')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_medias', to='course.company', verbose_name='Компания')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='course.company', verbose_name='Компания')),
            ],
        ),
    ]
